// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/array/banking-api/internal/services (interfaces: AccountAssociationServiceInterface,AccountServiceInterface,AccountMetricsServiceInterface,AccountSummaryServiceInterface,AuditServiceInterface,AuthServiceInterface,CategoryServiceInterface,CustomerProfileServiceInterface,CustomerSearchServiceInterface,PasswordServiceInterface,TokenServiceInterface,TransactionProcessingServiceInterface,TransactionGeneratorInterface,StatementServiceInterface,AuditLoggerInterface,MetricsRecorderInterface,CircuitBreakerInterface,CustomerLoggerInterface)

// Package service_mocks is a generated GoMock package.
package service_mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	dto "github.com/array/banking-api/internal/dto"
	models "github.com/array/banking-api/internal/models"
	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
	decimal "github.com/shopspring/decimal"
)

// MockAccountAssociationServiceInterface is a mock of AccountAssociationServiceInterface interface.
type MockAccountAssociationServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockAccountAssociationServiceInterfaceMockRecorder
}

// MockAccountAssociationServiceInterfaceMockRecorder is the mock recorder for MockAccountAssociationServiceInterface.
type MockAccountAssociationServiceInterfaceMockRecorder struct {
	mock *MockAccountAssociationServiceInterface
}

// NewMockAccountAssociationServiceInterface creates a new mock instance.
func NewMockAccountAssociationServiceInterface(ctrl *gomock.Controller) *MockAccountAssociationServiceInterface {
	mock := &MockAccountAssociationServiceInterface{ctrl: ctrl}
	mock.recorder = &MockAccountAssociationServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAccountAssociationServiceInterface) EXPECT() *MockAccountAssociationServiceInterfaceMockRecorder {
	return m.recorder
}

// CreateAccountForCustomer mocks base method.
func (m *MockAccountAssociationServiceInterface) CreateAccountForCustomer(arg0, arg1 uuid.UUID, arg2, arg3, arg4 string) (*models.Account, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAccountForCustomer", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].(*models.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateAccountForCustomer indicates an expected call of CreateAccountForCustomer.
func (mr *MockAccountAssociationServiceInterfaceMockRecorder) CreateAccountForCustomer(arg0, arg1, arg2, arg3, arg4 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAccountForCustomer", reflect.TypeOf((*MockAccountAssociationServiceInterface)(nil).CreateAccountForCustomer), arg0, arg1, arg2, arg3, arg4)
}

// GetCustomerAccounts mocks base method.
func (m *MockAccountAssociationServiceInterface) GetCustomerAccounts(arg0 uuid.UUID) ([]*models.Account, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCustomerAccounts", arg0)
	ret0, _ := ret[0].([]*models.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCustomerAccounts indicates an expected call of GetCustomerAccounts.
func (mr *MockAccountAssociationServiceInterfaceMockRecorder) GetCustomerAccounts(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCustomerAccounts", reflect.TypeOf((*MockAccountAssociationServiceInterface)(nil).GetCustomerAccounts), arg0)
}

// TransferAccountOwnership mocks base method.
func (m *MockAccountAssociationServiceInterface) TransferAccountOwnership(arg0, arg1, arg2, arg3 uuid.UUID, arg4, arg5 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TransferAccountOwnership", arg0, arg1, arg2, arg3, arg4, arg5)
	ret0, _ := ret[0].(error)
	return ret0
}

// TransferAccountOwnership indicates an expected call of TransferAccountOwnership.
func (mr *MockAccountAssociationServiceInterfaceMockRecorder) TransferAccountOwnership(arg0, arg1, arg2, arg3, arg4, arg5 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TransferAccountOwnership", reflect.TypeOf((*MockAccountAssociationServiceInterface)(nil).TransferAccountOwnership), arg0, arg1, arg2, arg3, arg4, arg5)
}

// MockAccountServiceInterface is a mock of AccountServiceInterface interface.
type MockAccountServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockAccountServiceInterfaceMockRecorder
}

// MockAccountServiceInterfaceMockRecorder is the mock recorder for MockAccountServiceInterface.
type MockAccountServiceInterfaceMockRecorder struct {
	mock *MockAccountServiceInterface
}

// NewMockAccountServiceInterface creates a new mock instance.
func NewMockAccountServiceInterface(ctrl *gomock.Controller) *MockAccountServiceInterface {
	mock := &MockAccountServiceInterface{ctrl: ctrl}
	mock.recorder = &MockAccountServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAccountServiceInterface) EXPECT() *MockAccountServiceInterfaceMockRecorder {
	return m.recorder
}

// CloseAccount mocks base method.
func (m *MockAccountServiceInterface) CloseAccount(arg0, arg1 uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CloseAccount", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// CloseAccount indicates an expected call of CloseAccount.
func (mr *MockAccountServiceInterfaceMockRecorder) CloseAccount(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CloseAccount", reflect.TypeOf((*MockAccountServiceInterface)(nil).CloseAccount), arg0, arg1)
}

// CreateAccount mocks base method.
func (m *MockAccountServiceInterface) CreateAccount(arg0 uuid.UUID, arg1, arg2, arg3, arg4 string, arg5 decimal.Decimal) (*models.Account, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAccount", arg0, arg1, arg2, arg3, arg4, arg5)
	ret0, _ := ret[0].(*models.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateAccount indicates an expected call of CreateAccount.
func (mr *MockAccountServiceInterfaceMockRecorder) CreateAccount(arg0, arg1, arg2, arg3, arg4, arg5 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAccount", reflect.TypeOf((*MockAccountServiceInterface)(nil).CreateAccount), arg0, arg1, arg2, arg3, arg4, arg5)
}

// CreateAccountsForNewUser mocks base method.
func (m *MockAccountServiceInterface) CreateAccountsForNewUser(arg0 uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAccountsForNewUser", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateAccountsForNewUser indicates an expected call of CreateAccountsForNewUser.
func (mr *MockAccountServiceInterfaceMockRecorder) CreateAccountsForNewUser(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAccountsForNewUser", reflect.TypeOf((*MockAccountServiceInterface)(nil).CreateAccountsForNewUser), arg0)
}

// GetAccountByID mocks base method.
func (m *MockAccountServiceInterface) GetAccountByID(arg0 uuid.UUID, arg1 *uuid.UUID) (*models.Account, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAccountByID", arg0, arg1)
	ret0, _ := ret[0].(*models.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAccountByID indicates an expected call of GetAccountByID.
func (mr *MockAccountServiceInterfaceMockRecorder) GetAccountByID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccountByID", reflect.TypeOf((*MockAccountServiceInterface)(nil).GetAccountByID), arg0, arg1)
}

// GetAccountByNumber mocks base method.
func (m *MockAccountServiceInterface) GetAccountByNumber(arg0 string) (*models.Account, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAccountByNumber", arg0)
	ret0, _ := ret[0].(*models.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAccountByNumber indicates an expected call of GetAccountByNumber.
func (mr *MockAccountServiceInterfaceMockRecorder) GetAccountByNumber(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccountByNumber", reflect.TypeOf((*MockAccountServiceInterface)(nil).GetAccountByNumber), arg0)
}

// GetAccountTransactions mocks base method.
func (m *MockAccountServiceInterface) GetAccountTransactions(arg0 uuid.UUID, arg1 *uuid.UUID, arg2, arg3 int) ([]models.Transaction, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAccountTransactions", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].([]models.Transaction)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetAccountTransactions indicates an expected call of GetAccountTransactions.
func (mr *MockAccountServiceInterfaceMockRecorder) GetAccountTransactions(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccountTransactions", reflect.TypeOf((*MockAccountServiceInterface)(nil).GetAccountTransactions), arg0, arg1, arg2, arg3)
}

// GetAllAccounts mocks base method.
func (m *MockAccountServiceInterface) GetAllAccounts(arg0 models.AccountFilters, arg1, arg2 int) ([]models.Account, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllAccounts", arg0, arg1, arg2)
	ret0, _ := ret[0].([]models.Account)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetAllAccounts indicates an expected call of GetAllAccounts.
func (mr *MockAccountServiceInterfaceMockRecorder) GetAllAccounts(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllAccounts", reflect.TypeOf((*MockAccountServiceInterface)(nil).GetAllAccounts), arg0, arg1, arg2)
}

// GetRecentTransactions mocks base method.
func (m *MockAccountServiceInterface) GetRecentTransactions(arg0 uuid.UUID, arg1 *uuid.UUID, arg2 int) ([]models.Transaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRecentTransactions", arg0, arg1, arg2)
	ret0, _ := ret[0].([]models.Transaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRecentTransactions indicates an expected call of GetRecentTransactions.
func (mr *MockAccountServiceInterfaceMockRecorder) GetRecentTransactions(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRecentTransactions", reflect.TypeOf((*MockAccountServiceInterface)(nil).GetRecentTransactions), arg0, arg1, arg2)
}

// GetUserAccounts mocks base method.
func (m *MockAccountServiceInterface) GetUserAccounts(arg0 uuid.UUID) ([]models.Account, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserAccounts", arg0)
	ret0, _ := ret[0].([]models.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserAccounts indicates an expected call of GetUserAccounts.
func (mr *MockAccountServiceInterfaceMockRecorder) GetUserAccounts(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserAccounts", reflect.TypeOf((*MockAccountServiceInterface)(nil).GetUserAccounts), arg0)
}

// GetUserTransfers mocks base method.
func (m *MockAccountServiceInterface) GetUserTransfers(arg0 uuid.UUID, arg1 models.TransferFilters, arg2, arg3 int) ([]models.Transfer, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserTransfers", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].([]models.Transfer)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetUserTransfers indicates an expected call of GetUserTransfers.
func (mr *MockAccountServiceInterfaceMockRecorder) GetUserTransfers(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserTransfers", reflect.TypeOf((*MockAccountServiceInterface)(nil).GetUserTransfers), arg0, arg1, arg2, arg3)
}

// PerformTransaction mocks base method.
func (m *MockAccountServiceInterface) PerformTransaction(arg0 uuid.UUID, arg1 decimal.Decimal, arg2, arg3 string, arg4 *uuid.UUID) (*models.Transaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PerformTransaction", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].(*models.Transaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PerformTransaction indicates an expected call of PerformTransaction.
func (mr *MockAccountServiceInterfaceMockRecorder) PerformTransaction(arg0, arg1, arg2, arg3, arg4 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PerformTransaction", reflect.TypeOf((*MockAccountServiceInterface)(nil).PerformTransaction), arg0, arg1, arg2, arg3, arg4)
}

// TransferBetweenAccounts mocks base method.
func (m *MockAccountServiceInterface) TransferBetweenAccounts(arg0 context.Context, arg1 dto.TransferBetweenAccountsInput) (*models.Transfer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TransferBetweenAccounts", arg0, arg1)
	ret0, _ := ret[0].(*models.Transfer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TransferBetweenAccounts indicates an expected call of TransferBetweenAccounts.
func (mr *MockAccountServiceInterfaceMockRecorder) TransferBetweenAccounts(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TransferBetweenAccounts", reflect.TypeOf((*MockAccountServiceInterface)(nil).TransferBetweenAccounts), arg0, arg1)
}

// UpdateAccountStatus mocks base method.
func (m *MockAccountServiceInterface) UpdateAccountStatus(arg0 uuid.UUID, arg1 *uuid.UUID, arg2 string) (*models.Account, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAccountStatus", arg0, arg1, arg2)
	ret0, _ := ret[0].(*models.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateAccountStatus indicates an expected call of UpdateAccountStatus.
func (mr *MockAccountServiceInterfaceMockRecorder) UpdateAccountStatus(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAccountStatus", reflect.TypeOf((*MockAccountServiceInterface)(nil).UpdateAccountStatus), arg0, arg1, arg2)
}

// MockAccountMetricsServiceInterface is a mock of AccountMetricsServiceInterface interface.
type MockAccountMetricsServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockAccountMetricsServiceInterfaceMockRecorder
}

// MockAccountMetricsServiceInterfaceMockRecorder is the mock recorder for MockAccountMetricsServiceInterface.
type MockAccountMetricsServiceInterfaceMockRecorder struct {
	mock *MockAccountMetricsServiceInterface
}

// NewMockAccountMetricsServiceInterface creates a new mock instance.
func NewMockAccountMetricsServiceInterface(ctrl *gomock.Controller) *MockAccountMetricsServiceInterface {
	mock := &MockAccountMetricsServiceInterface{ctrl: ctrl}
	mock.recorder = &MockAccountMetricsServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAccountMetricsServiceInterface) EXPECT() *MockAccountMetricsServiceInterfaceMockRecorder {
	return m.recorder
}

// GetAccountMetrics mocks base method.
func (m *MockAccountMetricsServiceInterface) GetAccountMetrics(arg0, arg1 uuid.UUID, arg2, arg3 *time.Time, arg4 bool) (*models.AccountMetrics, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAccountMetrics", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].(*models.AccountMetrics)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAccountMetrics indicates an expected call of GetAccountMetrics.
func (mr *MockAccountMetricsServiceInterfaceMockRecorder) GetAccountMetrics(arg0, arg1, arg2, arg3, arg4 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccountMetrics", reflect.TypeOf((*MockAccountMetricsServiceInterface)(nil).GetAccountMetrics), arg0, arg1, arg2, arg3, arg4)
}

// GetUserAggregateMetrics mocks base method.
func (m *MockAccountMetricsServiceInterface) GetUserAggregateMetrics(arg0, arg1 uuid.UUID, arg2, arg3 *time.Time, arg4 bool) (*models.UserAggregateMetrics, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserAggregateMetrics", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].(*models.UserAggregateMetrics)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserAggregateMetrics indicates an expected call of GetUserAggregateMetrics.
func (mr *MockAccountMetricsServiceInterfaceMockRecorder) GetUserAggregateMetrics(arg0, arg1, arg2, arg3, arg4 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserAggregateMetrics", reflect.TypeOf((*MockAccountMetricsServiceInterface)(nil).GetUserAggregateMetrics), arg0, arg1, arg2, arg3, arg4)
}

// MockAccountSummaryServiceInterface is a mock of AccountSummaryServiceInterface interface.
type MockAccountSummaryServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockAccountSummaryServiceInterfaceMockRecorder
}

// MockAccountSummaryServiceInterfaceMockRecorder is the mock recorder for MockAccountSummaryServiceInterface.
type MockAccountSummaryServiceInterfaceMockRecorder struct {
	mock *MockAccountSummaryServiceInterface
}

// NewMockAccountSummaryServiceInterface creates a new mock instance.
func NewMockAccountSummaryServiceInterface(ctrl *gomock.Controller) *MockAccountSummaryServiceInterface {
	mock := &MockAccountSummaryServiceInterface{ctrl: ctrl}
	mock.recorder = &MockAccountSummaryServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAccountSummaryServiceInterface) EXPECT() *MockAccountSummaryServiceInterfaceMockRecorder {
	return m.recorder
}

// GetAccountSummary mocks base method.
func (m *MockAccountSummaryServiceInterface) GetAccountSummary(arg0 uuid.UUID, arg1 *uuid.UUID, arg2 bool) (*models.UserAccountSummary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAccountSummary", arg0, arg1, arg2)
	ret0, _ := ret[0].(*models.UserAccountSummary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAccountSummary indicates an expected call of GetAccountSummary.
func (mr *MockAccountSummaryServiceInterfaceMockRecorder) GetAccountSummary(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccountSummary", reflect.TypeOf((*MockAccountSummaryServiceInterface)(nil).GetAccountSummary), arg0, arg1, arg2)
}

// MockAuditServiceInterface is a mock of AuditServiceInterface interface.
type MockAuditServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockAuditServiceInterfaceMockRecorder
}

// MockAuditServiceInterfaceMockRecorder is the mock recorder for MockAuditServiceInterface.
type MockAuditServiceInterfaceMockRecorder struct {
	mock *MockAuditServiceInterface
}

// NewMockAuditServiceInterface creates a new mock instance.
func NewMockAuditServiceInterface(ctrl *gomock.Controller) *MockAuditServiceInterface {
	mock := &MockAuditServiceInterface{ctrl: ctrl}
	mock.recorder = &MockAuditServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuditServiceInterface) EXPECT() *MockAuditServiceInterfaceMockRecorder {
	return m.recorder
}

// CreateAuditLog mocks base method.
func (m *MockAuditServiceInterface) CreateAuditLog(arg0 *models.AuditLog) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAuditLog", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateAuditLog indicates an expected call of CreateAuditLog.
func (mr *MockAuditServiceInterfaceMockRecorder) CreateAuditLog(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAuditLog", reflect.TypeOf((*MockAuditServiceInterface)(nil).CreateAuditLog), arg0)
}

// GetCustomerActivity mocks base method.
func (m *MockAuditServiceInterface) GetCustomerActivity(arg0 uuid.UUID, arg1, arg2 *time.Time, arg3, arg4 int) ([]*models.AuditLog, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCustomerActivity", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].([]*models.AuditLog)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetCustomerActivity indicates an expected call of GetCustomerActivity.
func (mr *MockAuditServiceInterfaceMockRecorder) GetCustomerActivity(arg0, arg1, arg2, arg3, arg4 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCustomerActivity", reflect.TypeOf((*MockAuditServiceInterface)(nil).GetCustomerActivity), arg0, arg1, arg2, arg3, arg4)
}

// LogAccountCreated mocks base method.
func (m *MockAuditServiceInterface) LogAccountCreated(arg0, arg1, arg2 uuid.UUID, arg3, arg4, arg5 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LogAccountCreated", arg0, arg1, arg2, arg3, arg4, arg5)
	ret0, _ := ret[0].(error)
	return ret0
}

// LogAccountCreated indicates an expected call of LogAccountCreated.
func (mr *MockAuditServiceInterfaceMockRecorder) LogAccountCreated(arg0, arg1, arg2, arg3, arg4, arg5 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LogAccountCreated", reflect.TypeOf((*MockAuditServiceInterface)(nil).LogAccountCreated), arg0, arg1, arg2, arg3, arg4, arg5)
}

// LogAccountTransferred mocks base method.
func (m *MockAuditServiceInterface) LogAccountTransferred(arg0, arg1, arg2, arg3 uuid.UUID, arg4, arg5 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LogAccountTransferred", arg0, arg1, arg2, arg3, arg4, arg5)
	ret0, _ := ret[0].(error)
	return ret0
}

// LogAccountTransferred indicates an expected call of LogAccountTransferred.
func (mr *MockAuditServiceInterfaceMockRecorder) LogAccountTransferred(arg0, arg1, arg2, arg3, arg4, arg5 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LogAccountTransferred", reflect.TypeOf((*MockAuditServiceInterface)(nil).LogAccountTransferred), arg0, arg1, arg2, arg3, arg4, arg5)
}

// LogCustomerCreated mocks base method.
func (m *MockAuditServiceInterface) LogCustomerCreated(arg0, arg1 uuid.UUID, arg2, arg3 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LogCustomerCreated", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(error)
	return ret0
}

// LogCustomerCreated indicates an expected call of LogCustomerCreated.
func (mr *MockAuditServiceInterfaceMockRecorder) LogCustomerCreated(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LogCustomerCreated", reflect.TypeOf((*MockAuditServiceInterface)(nil).LogCustomerCreated), arg0, arg1, arg2, arg3)
}

// LogCustomerDeleted mocks base method.
func (m *MockAuditServiceInterface) LogCustomerDeleted(arg0, arg1 uuid.UUID, arg2, arg3, arg4 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LogCustomerDeleted", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].(error)
	return ret0
}

// LogCustomerDeleted indicates an expected call of LogCustomerDeleted.
func (mr *MockAuditServiceInterfaceMockRecorder) LogCustomerDeleted(arg0, arg1, arg2, arg3, arg4 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LogCustomerDeleted", reflect.TypeOf((*MockAuditServiceInterface)(nil).LogCustomerDeleted), arg0, arg1, arg2, arg3, arg4)
}

// LogEmailUpdate mocks base method.
func (m *MockAuditServiceInterface) LogEmailUpdate(arg0, arg1 uuid.UUID, arg2, arg3, arg4, arg5 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LogEmailUpdate", arg0, arg1, arg2, arg3, arg4, arg5)
	ret0, _ := ret[0].(error)
	return ret0
}

// LogEmailUpdate indicates an expected call of LogEmailUpdate.
func (mr *MockAuditServiceInterfaceMockRecorder) LogEmailUpdate(arg0, arg1, arg2, arg3, arg4, arg5 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LogEmailUpdate", reflect.TypeOf((*MockAuditServiceInterface)(nil).LogEmailUpdate), arg0, arg1, arg2, arg3, arg4, arg5)
}

// LogLogin mocks base method.
func (m *MockAuditServiceInterface) LogLogin(arg0 uuid.UUID, arg1, arg2 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LogLogin", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// LogLogin indicates an expected call of LogLogin.
func (mr *MockAuditServiceInterfaceMockRecorder) LogLogin(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LogLogin", reflect.TypeOf((*MockAuditServiceInterface)(nil).LogLogin), arg0, arg1, arg2)
}

// LogLogout mocks base method.
func (m *MockAuditServiceInterface) LogLogout(arg0 uuid.UUID, arg1, arg2 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LogLogout", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// LogLogout indicates an expected call of LogLogout.
func (mr *MockAuditServiceInterfaceMockRecorder) LogLogout(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LogLogout", reflect.TypeOf((*MockAuditServiceInterface)(nil).LogLogout), arg0, arg1, arg2)
}

// LogPasswordReset mocks base method.
func (m *MockAuditServiceInterface) LogPasswordReset(arg0, arg1 uuid.UUID, arg2, arg3 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LogPasswordReset", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(error)
	return ret0
}

// LogPasswordReset indicates an expected call of LogPasswordReset.
func (mr *MockAuditServiceInterfaceMockRecorder) LogPasswordReset(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LogPasswordReset", reflect.TypeOf((*MockAuditServiceInterface)(nil).LogPasswordReset), arg0, arg1, arg2, arg3)
}

// LogPasswordUpdate mocks base method.
func (m *MockAuditServiceInterface) LogPasswordUpdate(arg0 uuid.UUID, arg1, arg2 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LogPasswordUpdate", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// LogPasswordUpdate indicates an expected call of LogPasswordUpdate.
func (mr *MockAuditServiceInterfaceMockRecorder) LogPasswordUpdate(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LogPasswordUpdate", reflect.TypeOf((*MockAuditServiceInterface)(nil).LogPasswordUpdate), arg0, arg1, arg2)
}

// LogProfileUpdate mocks base method.
func (m *MockAuditServiceInterface) LogProfileUpdate(arg0, arg1 uuid.UUID, arg2, arg3 string, arg4 map[string]interface{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LogProfileUpdate", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].(error)
	return ret0
}

// LogProfileUpdate indicates an expected call of LogProfileUpdate.
func (mr *MockAuditServiceInterfaceMockRecorder) LogProfileUpdate(arg0, arg1, arg2, arg3, arg4 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LogProfileUpdate", reflect.TypeOf((*MockAuditServiceInterface)(nil).LogProfileUpdate), arg0, arg1, arg2, arg3, arg4)
}

// MockAuthServiceInterface is a mock of AuthServiceInterface interface.
type MockAuthServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockAuthServiceInterfaceMockRecorder
}

// MockAuthServiceInterfaceMockRecorder is the mock recorder for MockAuthServiceInterface.
type MockAuthServiceInterfaceMockRecorder struct {
	mock *MockAuthServiceInterface
}

// NewMockAuthServiceInterface creates a new mock instance.
func NewMockAuthServiceInterface(ctrl *gomock.Controller) *MockAuthServiceInterface {
	mock := &MockAuthServiceInterface{ctrl: ctrl}
	mock.recorder = &MockAuthServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthServiceInterface) EXPECT() *MockAuthServiceInterfaceMockRecorder {
	return m.recorder
}

// Login mocks base method.
func (m *MockAuthServiceInterface) Login(arg0 *dto.LoginRequest, arg1, arg2 string) (*dto.TokenResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Login", arg0, arg1, arg2)
	ret0, _ := ret[0].(*dto.TokenResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Login indicates an expected call of Login.
func (mr *MockAuthServiceInterfaceMockRecorder) Login(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Login", reflect.TypeOf((*MockAuthServiceInterface)(nil).Login), arg0, arg1, arg2)
}

// Logout mocks base method.
func (m *MockAuthServiceInterface) Logout(arg0, arg1, arg2 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Logout", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// Logout indicates an expected call of Logout.
func (mr *MockAuthServiceInterfaceMockRecorder) Logout(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Logout", reflect.TypeOf((*MockAuthServiceInterface)(nil).Logout), arg0, arg1, arg2)
}

// RefreshTokens mocks base method.
func (m *MockAuthServiceInterface) RefreshTokens(arg0, arg1, arg2 string) (*dto.TokenResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RefreshTokens", arg0, arg1, arg2)
	ret0, _ := ret[0].(*dto.TokenResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RefreshTokens indicates an expected call of RefreshTokens.
func (mr *MockAuthServiceInterfaceMockRecorder) RefreshTokens(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RefreshTokens", reflect.TypeOf((*MockAuthServiceInterface)(nil).RefreshTokens), arg0, arg1, arg2)
}

// Register mocks base method.
func (m *MockAuthServiceInterface) Register(arg0 *dto.RegisterRequest, arg1, arg2 string) (*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Register", arg0, arg1, arg2)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Register indicates an expected call of Register.
func (mr *MockAuthServiceInterfaceMockRecorder) Register(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Register", reflect.TypeOf((*MockAuthServiceInterface)(nil).Register), arg0, arg1, arg2)
}

// MockCategoryServiceInterface is a mock of CategoryServiceInterface interface.
type MockCategoryServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockCategoryServiceInterfaceMockRecorder
}

// MockCategoryServiceInterfaceMockRecorder is the mock recorder for MockCategoryServiceInterface.
type MockCategoryServiceInterfaceMockRecorder struct {
	mock *MockCategoryServiceInterface
}

// NewMockCategoryServiceInterface creates a new mock instance.
func NewMockCategoryServiceInterface(ctrl *gomock.Controller) *MockCategoryServiceInterface {
	mock := &MockCategoryServiceInterface{ctrl: ctrl}
	mock.recorder = &MockCategoryServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCategoryServiceInterface) EXPECT() *MockCategoryServiceInterfaceMockRecorder {
	return m.recorder
}

// BatchCategorize mocks base method.
func (m *MockCategoryServiceInterface) BatchCategorize(arg0 []*models.Transaction) []*models.CategorizationResult {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchCategorize", arg0)
	ret0, _ := ret[0].([]*models.CategorizationResult)
	return ret0
}

// BatchCategorize indicates an expected call of BatchCategorize.
func (mr *MockCategoryServiceInterfaceMockRecorder) BatchCategorize(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchCategorize", reflect.TypeOf((*MockCategoryServiceInterface)(nil).BatchCategorize), arg0)
}

// CategorizeByDescription mocks base method.
func (m *MockCategoryServiceInterface) CategorizeByDescription(arg0 string) (string, float64) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CategorizeByDescription", arg0)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(float64)
	return ret0, ret1
}

// CategorizeByDescription indicates an expected call of CategorizeByDescription.
func (mr *MockCategoryServiceInterfaceMockRecorder) CategorizeByDescription(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CategorizeByDescription", reflect.TypeOf((*MockCategoryServiceInterface)(nil).CategorizeByDescription), arg0)
}

// CategorizeByMerchant mocks base method.
func (m *MockCategoryServiceInterface) CategorizeByMerchant(arg0 string) (string, float64) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CategorizeByMerchant", arg0)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(float64)
	return ret0, ret1
}

// CategorizeByMerchant indicates an expected call of CategorizeByMerchant.
func (mr *MockCategoryServiceInterfaceMockRecorder) CategorizeByMerchant(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CategorizeByMerchant", reflect.TypeOf((*MockCategoryServiceInterface)(nil).CategorizeByMerchant), arg0)
}

// CategorizeTransaction mocks base method.
func (m *MockCategoryServiceInterface) CategorizeTransaction(arg0 *models.Transaction) *models.CategorizationResult {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CategorizeTransaction", arg0)
	ret0, _ := ret[0].(*models.CategorizationResult)
	return ret0
}

// CategorizeTransaction indicates an expected call of CategorizeTransaction.
func (mr *MockCategoryServiceInterfaceMockRecorder) CategorizeTransaction(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CategorizeTransaction", reflect.TypeOf((*MockCategoryServiceInterface)(nil).CategorizeTransaction), arg0)
}

// CategoryFromMCC mocks base method.
func (m *MockCategoryServiceInterface) CategoryFromMCC(arg0 string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CategoryFromMCC", arg0)
	ret0, _ := ret[0].(string)
	return ret0
}

// CategoryFromMCC indicates an expected call of CategoryFromMCC.
func (mr *MockCategoryServiceInterfaceMockRecorder) CategoryFromMCC(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CategoryFromMCC", reflect.TypeOf((*MockCategoryServiceInterface)(nil).CategoryFromMCC), arg0)
}

// FuzzyMatchMerchant mocks base method.
func (m *MockCategoryServiceInterface) FuzzyMatchMerchant(arg0 string) (string, float64) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FuzzyMatchMerchant", arg0)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(float64)
	return ret0, ret1
}

// FuzzyMatchMerchant indicates an expected call of FuzzyMatchMerchant.
func (mr *MockCategoryServiceInterfaceMockRecorder) FuzzyMatchMerchant(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FuzzyMatchMerchant", reflect.TypeOf((*MockCategoryServiceInterface)(nil).FuzzyMatchMerchant), arg0)
}

// OverrideCategory mocks base method.
func (m *MockCategoryServiceInterface) OverrideCategory(arg0 *models.Transaction, arg1, arg2 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OverrideCategory", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// OverrideCategory indicates an expected call of OverrideCategory.
func (mr *MockCategoryServiceInterfaceMockRecorder) OverrideCategory(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OverrideCategory", reflect.TypeOf((*MockCategoryServiceInterface)(nil).OverrideCategory), arg0, arg1, arg2)
}

// MockCustomerProfileServiceInterface is a mock of CustomerProfileServiceInterface interface.
type MockCustomerProfileServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockCustomerProfileServiceInterfaceMockRecorder
}

// MockCustomerProfileServiceInterfaceMockRecorder is the mock recorder for MockCustomerProfileServiceInterface.
type MockCustomerProfileServiceInterfaceMockRecorder struct {
	mock *MockCustomerProfileServiceInterface
}

// NewMockCustomerProfileServiceInterface creates a new mock instance.
func NewMockCustomerProfileServiceInterface(ctrl *gomock.Controller) *MockCustomerProfileServiceInterface {
	mock := &MockCustomerProfileServiceInterface{ctrl: ctrl}
	mock.recorder = &MockCustomerProfileServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCustomerProfileServiceInterface) EXPECT() *MockCustomerProfileServiceInterfaceMockRecorder {
	return m.recorder
}

// CreateCustomer mocks base method.
func (m *MockCustomerProfileServiceInterface) CreateCustomer(arg0, arg1, arg2, arg3 string) (*models.User, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCustomer", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// CreateCustomer indicates an expected call of CreateCustomer.
func (mr *MockCustomerProfileServiceInterfaceMockRecorder) CreateCustomer(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCustomer", reflect.TypeOf((*MockCustomerProfileServiceInterface)(nil).CreateCustomer), arg0, arg1, arg2, arg3)
}

// DeleteCustomer mocks base method.
func (m *MockCustomerProfileServiceInterface) DeleteCustomer(arg0 uuid.UUID, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteCustomer", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteCustomer indicates an expected call of DeleteCustomer.
func (mr *MockCustomerProfileServiceInterfaceMockRecorder) DeleteCustomer(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCustomer", reflect.TypeOf((*MockCustomerProfileServiceInterface)(nil).DeleteCustomer), arg0, arg1)
}

// GetCustomerProfile mocks base method.
func (m *MockCustomerProfileServiceInterface) GetCustomerProfile(arg0 uuid.UUID) (*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCustomerProfile", arg0)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCustomerProfile indicates an expected call of GetCustomerProfile.
func (mr *MockCustomerProfileServiceInterfaceMockRecorder) GetCustomerProfile(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCustomerProfile", reflect.TypeOf((*MockCustomerProfileServiceInterface)(nil).GetCustomerProfile), arg0)
}

// UpdateCustomerEmail mocks base method.
func (m *MockCustomerProfileServiceInterface) UpdateCustomerEmail(arg0 uuid.UUID, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCustomerEmail", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateCustomerEmail indicates an expected call of UpdateCustomerEmail.
func (mr *MockCustomerProfileServiceInterfaceMockRecorder) UpdateCustomerEmail(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCustomerEmail", reflect.TypeOf((*MockCustomerProfileServiceInterface)(nil).UpdateCustomerEmail), arg0, arg1)
}

// UpdateCustomerProfile mocks base method.
func (m *MockCustomerProfileServiceInterface) UpdateCustomerProfile(arg0 uuid.UUID, arg1 map[string]interface{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCustomerProfile", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateCustomerProfile indicates an expected call of UpdateCustomerProfile.
func (mr *MockCustomerProfileServiceInterfaceMockRecorder) UpdateCustomerProfile(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCustomerProfile", reflect.TypeOf((*MockCustomerProfileServiceInterface)(nil).UpdateCustomerProfile), arg0, arg1)
}

// MockCustomerSearchServiceInterface is a mock of CustomerSearchServiceInterface interface.
type MockCustomerSearchServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockCustomerSearchServiceInterfaceMockRecorder
}

// MockCustomerSearchServiceInterfaceMockRecorder is the mock recorder for MockCustomerSearchServiceInterface.
type MockCustomerSearchServiceInterfaceMockRecorder struct {
	mock *MockCustomerSearchServiceInterface
}

// NewMockCustomerSearchServiceInterface creates a new mock instance.
func NewMockCustomerSearchServiceInterface(ctrl *gomock.Controller) *MockCustomerSearchServiceInterface {
	mock := &MockCustomerSearchServiceInterface{ctrl: ctrl}
	mock.recorder = &MockCustomerSearchServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCustomerSearchServiceInterface) EXPECT() *MockCustomerSearchServiceInterfaceMockRecorder {
	return m.recorder
}

// SearchCustomers mocks base method.
func (m *MockCustomerSearchServiceInterface) SearchCustomers(arg0 string, arg1 models.SearchType, arg2, arg3 int) ([]*models.CustomerSearchResult, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchCustomers", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].([]*models.CustomerSearchResult)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// SearchCustomers indicates an expected call of SearchCustomers.
func (mr *MockCustomerSearchServiceInterfaceMockRecorder) SearchCustomers(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchCustomers", reflect.TypeOf((*MockCustomerSearchServiceInterface)(nil).SearchCustomers), arg0, arg1, arg2, arg3)
}

// MockPasswordServiceInterface is a mock of PasswordServiceInterface interface.
type MockPasswordServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockPasswordServiceInterfaceMockRecorder
}

// MockPasswordServiceInterfaceMockRecorder is the mock recorder for MockPasswordServiceInterface.
type MockPasswordServiceInterfaceMockRecorder struct {
	mock *MockPasswordServiceInterface
}

// NewMockPasswordServiceInterface creates a new mock instance.
func NewMockPasswordServiceInterface(ctrl *gomock.Controller) *MockPasswordServiceInterface {
	mock := &MockPasswordServiceInterface{ctrl: ctrl}
	mock.recorder = &MockPasswordServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPasswordServiceInterface) EXPECT() *MockPasswordServiceInterfaceMockRecorder {
	return m.recorder
}

// AdminResetPassword mocks base method.
func (m *MockPasswordServiceInterface) AdminResetPassword(arg0, arg1 uuid.UUID) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AdminResetPassword", arg0, arg1)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AdminResetPassword indicates an expected call of AdminResetPassword.
func (mr *MockPasswordServiceInterfaceMockRecorder) AdminResetPassword(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AdminResetPassword", reflect.TypeOf((*MockPasswordServiceInterface)(nil).AdminResetPassword), arg0, arg1)
}

// ComparePassword mocks base method.
func (m *MockPasswordServiceInterface) ComparePassword(arg0, arg1 string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ComparePassword", arg0, arg1)
	ret0, _ := ret[0].(bool)
	return ret0
}

// ComparePassword indicates an expected call of ComparePassword.
func (mr *MockPasswordServiceInterfaceMockRecorder) ComparePassword(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ComparePassword", reflect.TypeOf((*MockPasswordServiceInterface)(nil).ComparePassword), arg0, arg1)
}

// CustomerUpdatePassword mocks base method.
func (m *MockPasswordServiceInterface) CustomerUpdatePassword(arg0 uuid.UUID, arg1, arg2 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CustomerUpdatePassword", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// CustomerUpdatePassword indicates an expected call of CustomerUpdatePassword.
func (mr *MockPasswordServiceInterfaceMockRecorder) CustomerUpdatePassword(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CustomerUpdatePassword", reflect.TypeOf((*MockPasswordServiceInterface)(nil).CustomerUpdatePassword), arg0, arg1, arg2)
}

// GenerateSecurePassword mocks base method.
func (m *MockPasswordServiceInterface) GenerateSecurePassword() (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateSecurePassword")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateSecurePassword indicates an expected call of GenerateSecurePassword.
func (mr *MockPasswordServiceInterfaceMockRecorder) GenerateSecurePassword() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateSecurePassword", reflect.TypeOf((*MockPasswordServiceInterface)(nil).GenerateSecurePassword))
}

// GenerateSecurePasswordWithLength mocks base method.
func (m *MockPasswordServiceInterface) GenerateSecurePasswordWithLength(arg0 int) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateSecurePasswordWithLength", arg0)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateSecurePasswordWithLength indicates an expected call of GenerateSecurePasswordWithLength.
func (mr *MockPasswordServiceInterfaceMockRecorder) GenerateSecurePasswordWithLength(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateSecurePasswordWithLength", reflect.TypeOf((*MockPasswordServiceInterface)(nil).GenerateSecurePasswordWithLength), arg0)
}

// HashPassword mocks base method.
func (m *MockPasswordServiceInterface) HashPassword(arg0 string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HashPassword", arg0)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HashPassword indicates an expected call of HashPassword.
func (mr *MockPasswordServiceInterfaceMockRecorder) HashPassword(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HashPassword", reflect.TypeOf((*MockPasswordServiceInterface)(nil).HashPassword), arg0)
}

// HashPasswordWithoutValidation mocks base method.
func (m *MockPasswordServiceInterface) HashPasswordWithoutValidation(arg0 string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HashPasswordWithoutValidation", arg0)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HashPasswordWithoutValidation indicates an expected call of HashPasswordWithoutValidation.
func (mr *MockPasswordServiceInterfaceMockRecorder) HashPasswordWithoutValidation(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HashPasswordWithoutValidation", reflect.TypeOf((*MockPasswordServiceInterface)(nil).HashPasswordWithoutValidation), arg0)
}

// PasswordStrength mocks base method.
func (m *MockPasswordServiceInterface) PasswordStrength(arg0 string) int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PasswordStrength", arg0)
	ret0, _ := ret[0].(int)
	return ret0
}

// PasswordStrength indicates an expected call of PasswordStrength.
func (mr *MockPasswordServiceInterfaceMockRecorder) PasswordStrength(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PasswordStrength", reflect.TypeOf((*MockPasswordServiceInterface)(nil).PasswordStrength), arg0)
}

// ValidatePassword mocks base method.
func (m *MockPasswordServiceInterface) ValidatePassword(arg0 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidatePassword", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// ValidatePassword indicates an expected call of ValidatePassword.
func (mr *MockPasswordServiceInterfaceMockRecorder) ValidatePassword(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidatePassword", reflect.TypeOf((*MockPasswordServiceInterface)(nil).ValidatePassword), arg0)
}

// MockTokenServiceInterface is a mock of TokenServiceInterface interface.
type MockTokenServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockTokenServiceInterfaceMockRecorder
}

// MockTokenServiceInterfaceMockRecorder is the mock recorder for MockTokenServiceInterface.
type MockTokenServiceInterfaceMockRecorder struct {
	mock *MockTokenServiceInterface
}

// NewMockTokenServiceInterface creates a new mock instance.
func NewMockTokenServiceInterface(ctrl *gomock.Controller) *MockTokenServiceInterface {
	mock := &MockTokenServiceInterface{ctrl: ctrl}
	mock.recorder = &MockTokenServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTokenServiceInterface) EXPECT() *MockTokenServiceInterfaceMockRecorder {
	return m.recorder
}

// ExtractTokenFromHeader mocks base method.
func (m *MockTokenServiceInterface) ExtractTokenFromHeader(arg0 string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExtractTokenFromHeader", arg0)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExtractTokenFromHeader indicates an expected call of ExtractTokenFromHeader.
func (mr *MockTokenServiceInterfaceMockRecorder) ExtractTokenFromHeader(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExtractTokenFromHeader", reflect.TypeOf((*MockTokenServiceInterface)(nil).ExtractTokenFromHeader), arg0)
}

// GenerateAccessToken mocks base method.
func (m *MockTokenServiceInterface) GenerateAccessToken(arg0 *models.User) (string, time.Time, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateAccessToken", arg0)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(time.Time)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GenerateAccessToken indicates an expected call of GenerateAccessToken.
func (mr *MockTokenServiceInterfaceMockRecorder) GenerateAccessToken(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateAccessToken", reflect.TypeOf((*MockTokenServiceInterface)(nil).GenerateAccessToken), arg0)
}

// GenerateRefreshToken mocks base method.
func (m *MockTokenServiceInterface) GenerateRefreshToken(arg0 uuid.UUID) (string, time.Time, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateRefreshToken", arg0)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(time.Time)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GenerateRefreshToken indicates an expected call of GenerateRefreshToken.
func (mr *MockTokenServiceInterfaceMockRecorder) GenerateRefreshToken(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateRefreshToken", reflect.TypeOf((*MockTokenServiceInterface)(nil).GenerateRefreshToken), arg0)
}

// GetJTI mocks base method.
func (m *MockTokenServiceInterface) GetJTI(arg0 string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetJTI", arg0)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetJTI indicates an expected call of GetJTI.
func (mr *MockTokenServiceInterfaceMockRecorder) GetJTI(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetJTI", reflect.TypeOf((*MockTokenServiceInterface)(nil).GetJTI), arg0)
}

// GetTokenExpiry mocks base method.
func (m *MockTokenServiceInterface) GetTokenExpiry(arg0 string) (time.Time, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTokenExpiry", arg0)
	ret0, _ := ret[0].(time.Time)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTokenExpiry indicates an expected call of GetTokenExpiry.
func (mr *MockTokenServiceInterfaceMockRecorder) GetTokenExpiry(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTokenExpiry", reflect.TypeOf((*MockTokenServiceInterface)(nil).GetTokenExpiry), arg0)
}

// ValidateAccessToken mocks base method.
func (m *MockTokenServiceInterface) ValidateAccessToken(arg0 string) (*models.CustomClaims, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateAccessToken", arg0)
	ret0, _ := ret[0].(*models.CustomClaims)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ValidateAccessToken indicates an expected call of ValidateAccessToken.
func (mr *MockTokenServiceInterfaceMockRecorder) ValidateAccessToken(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateAccessToken", reflect.TypeOf((*MockTokenServiceInterface)(nil).ValidateAccessToken), arg0)
}

// ValidateRefreshToken mocks base method.
func (m *MockTokenServiceInterface) ValidateRefreshToken(arg0 string) (*models.CustomClaims, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateRefreshToken", arg0)
	ret0, _ := ret[0].(*models.CustomClaims)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ValidateRefreshToken indicates an expected call of ValidateRefreshToken.
func (mr *MockTokenServiceInterfaceMockRecorder) ValidateRefreshToken(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateRefreshToken", reflect.TypeOf((*MockTokenServiceInterface)(nil).ValidateRefreshToken), arg0)
}

// MockTransactionProcessingServiceInterface is a mock of TransactionProcessingServiceInterface interface.
type MockTransactionProcessingServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockTransactionProcessingServiceInterfaceMockRecorder
}

// MockTransactionProcessingServiceInterfaceMockRecorder is the mock recorder for MockTransactionProcessingServiceInterface.
type MockTransactionProcessingServiceInterfaceMockRecorder struct {
	mock *MockTransactionProcessingServiceInterface
}

// NewMockTransactionProcessingServiceInterface creates a new mock instance.
func NewMockTransactionProcessingServiceInterface(ctrl *gomock.Controller) *MockTransactionProcessingServiceInterface {
	mock := &MockTransactionProcessingServiceInterface{ctrl: ctrl}
	mock.recorder = &MockTransactionProcessingServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTransactionProcessingServiceInterface) EXPECT() *MockTransactionProcessingServiceInterfaceMockRecorder {
	return m.recorder
}

// EnqueueTransaction mocks base method.
func (m *MockTransactionProcessingServiceInterface) EnqueueTransaction(arg0 uuid.UUID, arg1 string, arg2 int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnqueueTransaction", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// EnqueueTransaction indicates an expected call of EnqueueTransaction.
func (mr *MockTransactionProcessingServiceInterfaceMockRecorder) EnqueueTransaction(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnqueueTransaction", reflect.TypeOf((*MockTransactionProcessingServiceInterface)(nil).EnqueueTransaction), arg0, arg1, arg2)
}

// GetQueueMetrics mocks base method.
func (m *MockTransactionProcessingServiceInterface) GetQueueMetrics() (*dto.QueueMetrics, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetQueueMetrics")
	ret0, _ := ret[0].(*dto.QueueMetrics)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetQueueMetrics indicates an expected call of GetQueueMetrics.
func (mr *MockTransactionProcessingServiceInterfaceMockRecorder) GetQueueMetrics() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetQueueMetrics", reflect.TypeOf((*MockTransactionProcessingServiceInterface)(nil).GetQueueMetrics))
}

// ProcessQueueItem mocks base method.
func (m *MockTransactionProcessingServiceInterface) ProcessQueueItem(arg0 context.Context, arg1 *models.ProcessingQueueItem) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProcessQueueItem", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// ProcessQueueItem indicates an expected call of ProcessQueueItem.
func (mr *MockTransactionProcessingServiceInterfaceMockRecorder) ProcessQueueItem(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProcessQueueItem", reflect.TypeOf((*MockTransactionProcessingServiceInterface)(nil).ProcessQueueItem), arg0, arg1)
}

// StartProcessing mocks base method.
func (m *MockTransactionProcessingServiceInterface) StartProcessing(arg0 context.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "StartProcessing", arg0)
}

// StartProcessing indicates an expected call of StartProcessing.
func (mr *MockTransactionProcessingServiceInterfaceMockRecorder) StartProcessing(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartProcessing", reflect.TypeOf((*MockTransactionProcessingServiceInterface)(nil).StartProcessing), arg0)
}

// MockTransactionGeneratorInterface is a mock of TransactionGeneratorInterface interface.
type MockTransactionGeneratorInterface struct {
	ctrl     *gomock.Controller
	recorder *MockTransactionGeneratorInterfaceMockRecorder
}

// MockTransactionGeneratorInterfaceMockRecorder is the mock recorder for MockTransactionGeneratorInterface.
type MockTransactionGeneratorInterfaceMockRecorder struct {
	mock *MockTransactionGeneratorInterface
}

// NewMockTransactionGeneratorInterface creates a new mock instance.
func NewMockTransactionGeneratorInterface(ctrl *gomock.Controller) *MockTransactionGeneratorInterface {
	mock := &MockTransactionGeneratorInterface{ctrl: ctrl}
	mock.recorder = &MockTransactionGeneratorInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTransactionGeneratorInterface) EXPECT() *MockTransactionGeneratorInterfaceMockRecorder {
	return m.recorder
}

// GenerateAmount mocks base method.
func (m *MockTransactionGeneratorInterface) GenerateAmount(arg0 string) decimal.Decimal {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateAmount", arg0)
	ret0, _ := ret[0].(decimal.Decimal)
	return ret0
}

// GenerateAmount indicates an expected call of GenerateAmount.
func (mr *MockTransactionGeneratorInterfaceMockRecorder) GenerateAmount(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateAmount", reflect.TypeOf((*MockTransactionGeneratorInterface)(nil).GenerateAmount), arg0)
}

// GenerateBillTransactions mocks base method.
func (m *MockTransactionGeneratorInterface) GenerateBillTransactions(arg0 uuid.UUID, arg1, arg2 time.Time, arg3 decimal.Decimal) []*models.Transaction {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateBillTransactions", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].([]*models.Transaction)
	return ret0
}

// GenerateBillTransactions indicates an expected call of GenerateBillTransactions.
func (mr *MockTransactionGeneratorInterfaceMockRecorder) GenerateBillTransactions(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateBillTransactions", reflect.TypeOf((*MockTransactionGeneratorInterface)(nil).GenerateBillTransactions), arg0, arg1, arg2, arg3)
}

// GenerateDailyPurchases mocks base method.
func (m *MockTransactionGeneratorInterface) GenerateDailyPurchases(arg0 uuid.UUID, arg1, arg2 time.Time, arg3 decimal.Decimal) []*models.Transaction {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateDailyPurchases", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].([]*models.Transaction)
	return ret0
}

// GenerateDailyPurchases indicates an expected call of GenerateDailyPurchases.
func (mr *MockTransactionGeneratorInterfaceMockRecorder) GenerateDailyPurchases(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateDailyPurchases", reflect.TypeOf((*MockTransactionGeneratorInterface)(nil).GenerateDailyPurchases), arg0, arg1, arg2, arg3)
}

// GenerateFeeAmount mocks base method.
func (m *MockTransactionGeneratorInterface) GenerateFeeAmount() decimal.Decimal {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateFeeAmount")
	ret0, _ := ret[0].(decimal.Decimal)
	return ret0
}

// GenerateFeeAmount indicates an expected call of GenerateFeeAmount.
func (mr *MockTransactionGeneratorInterfaceMockRecorder) GenerateFeeAmount() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateFeeAmount", reflect.TypeOf((*MockTransactionGeneratorInterface)(nil).GenerateFeeAmount))
}

// GenerateHistoricalTransactions mocks base method.
func (m *MockTransactionGeneratorInterface) GenerateHistoricalTransactions(arg0 uuid.UUID, arg1, arg2 time.Time, arg3 decimal.Decimal, arg4 int) []*models.Transaction {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateHistoricalTransactions", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].([]*models.Transaction)
	return ret0
}

// GenerateHistoricalTransactions indicates an expected call of GenerateHistoricalTransactions.
func (mr *MockTransactionGeneratorInterfaceMockRecorder) GenerateHistoricalTransactions(arg0, arg1, arg2, arg3, arg4 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateHistoricalTransactions", reflect.TypeOf((*MockTransactionGeneratorInterface)(nil).GenerateHistoricalTransactions), arg0, arg1, arg2, arg3, arg4)
}

// GenerateSalaryTransactions mocks base method.
func (m *MockTransactionGeneratorInterface) GenerateSalaryTransactions(arg0 uuid.UUID, arg1, arg2 time.Time, arg3 decimal.Decimal) []*models.Transaction {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateSalaryTransactions", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].([]*models.Transaction)
	return ret0
}

// GenerateSalaryTransactions indicates an expected call of GenerateSalaryTransactions.
func (mr *MockTransactionGeneratorInterfaceMockRecorder) GenerateSalaryTransactions(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateSalaryTransactions", reflect.TypeOf((*MockTransactionGeneratorInterface)(nil).GenerateSalaryTransactions), arg0, arg1, arg2, arg3)
}

// GenerateTimestamp mocks base method.
func (m *MockTransactionGeneratorInterface) GenerateTimestamp(arg0, arg1 time.Time) time.Time {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateTimestamp", arg0, arg1)
	ret0, _ := ret[0].(time.Time)
	return ret0
}

// GenerateTimestamp indicates an expected call of GenerateTimestamp.
func (mr *MockTransactionGeneratorInterfaceMockRecorder) GenerateTimestamp(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateTimestamp", reflect.TypeOf((*MockTransactionGeneratorInterface)(nil).GenerateTimestamp), arg0, arg1)
}

// GenerateTransactionType mocks base method.
func (m *MockTransactionGeneratorInterface) GenerateTransactionType() (string, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateTransactionType")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// GenerateTransactionType indicates an expected call of GenerateTransactionType.
func (mr *MockTransactionGeneratorInterfaceMockRecorder) GenerateTransactionType() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateTransactionType", reflect.TypeOf((*MockTransactionGeneratorInterface)(nil).GenerateTransactionType))
}

// GetMerchantPool mocks base method.
func (m *MockTransactionGeneratorInterface) GetMerchantPool() []models.MerchantInfo {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMerchantPool")
	ret0, _ := ret[0].([]models.MerchantInfo)
	return ret0
}

// GetMerchantPool indicates an expected call of GetMerchantPool.
func (mr *MockTransactionGeneratorInterfaceMockRecorder) GetMerchantPool() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMerchantPool", reflect.TypeOf((*MockTransactionGeneratorInterface)(nil).GetMerchantPool))
}

// SelectRandomMerchant mocks base method.
func (m *MockTransactionGeneratorInterface) SelectRandomMerchant() models.MerchantInfo {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SelectRandomMerchant")
	ret0, _ := ret[0].(models.MerchantInfo)
	return ret0
}

// SelectRandomMerchant indicates an expected call of SelectRandomMerchant.
func (mr *MockTransactionGeneratorInterfaceMockRecorder) SelectRandomMerchant() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SelectRandomMerchant", reflect.TypeOf((*MockTransactionGeneratorInterface)(nil).SelectRandomMerchant))
}

// MockStatementServiceInterface is a mock of StatementServiceInterface interface.
type MockStatementServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockStatementServiceInterfaceMockRecorder
}

// MockStatementServiceInterfaceMockRecorder is the mock recorder for MockStatementServiceInterface.
type MockStatementServiceInterfaceMockRecorder struct {
	mock *MockStatementServiceInterface
}

// NewMockStatementServiceInterface creates a new mock instance.
func NewMockStatementServiceInterface(ctrl *gomock.Controller) *MockStatementServiceInterface {
	mock := &MockStatementServiceInterface{ctrl: ctrl}
	mock.recorder = &MockStatementServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStatementServiceInterface) EXPECT() *MockStatementServiceInterfaceMockRecorder {
	return m.recorder
}

// GenerateStatement mocks base method.
func (m *MockStatementServiceInterface) GenerateStatement(arg0, arg1 uuid.UUID, arg2 string, arg3, arg4 int, arg5 bool) (*models.AccountStatement, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateStatement", arg0, arg1, arg2, arg3, arg4, arg5)
	ret0, _ := ret[0].(*models.AccountStatement)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateStatement indicates an expected call of GenerateStatement.
func (mr *MockStatementServiceInterfaceMockRecorder) GenerateStatement(arg0, arg1, arg2, arg3, arg4, arg5 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateStatement", reflect.TypeOf((*MockStatementServiceInterface)(nil).GenerateStatement), arg0, arg1, arg2, arg3, arg4, arg5)
}

// MockAuditLoggerInterface is a mock of AuditLoggerInterface interface.
type MockAuditLoggerInterface struct {
	ctrl     *gomock.Controller
	recorder *MockAuditLoggerInterfaceMockRecorder
}

// MockAuditLoggerInterfaceMockRecorder is the mock recorder for MockAuditLoggerInterface.
type MockAuditLoggerInterfaceMockRecorder struct {
	mock *MockAuditLoggerInterface
}

// NewMockAuditLoggerInterface creates a new mock instance.
func NewMockAuditLoggerInterface(ctrl *gomock.Controller) *MockAuditLoggerInterface {
	mock := &MockAuditLoggerInterface{ctrl: ctrl}
	mock.recorder = &MockAuditLoggerInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuditLoggerInterface) EXPECT() *MockAuditLoggerInterfaceMockRecorder {
	return m.recorder
}

// LogBalanceUpdate mocks base method.
func (m *MockAuditLoggerInterface) LogBalanceUpdate(arg0 context.Context, arg1 uuid.UUID, arg2, arg3 string, arg4 uuid.UUID) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "LogBalanceUpdate", arg0, arg1, arg2, arg3, arg4)
}

// LogBalanceUpdate indicates an expected call of LogBalanceUpdate.
func (mr *MockAuditLoggerInterfaceMockRecorder) LogBalanceUpdate(arg0, arg1, arg2, arg3, arg4 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LogBalanceUpdate", reflect.TypeOf((*MockAuditLoggerInterface)(nil).LogBalanceUpdate), arg0, arg1, arg2, arg3, arg4)
}

// LogCircuitBreakerStateChange mocks base method.
func (m *MockAuditLoggerInterface) LogCircuitBreakerStateChange(arg0 context.Context, arg1, arg2, arg3 string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "LogCircuitBreakerStateChange", arg0, arg1, arg2, arg3)
}

// LogCircuitBreakerStateChange indicates an expected call of LogCircuitBreakerStateChange.
func (mr *MockAuditLoggerInterfaceMockRecorder) LogCircuitBreakerStateChange(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LogCircuitBreakerStateChange", reflect.TypeOf((*MockAuditLoggerInterface)(nil).LogCircuitBreakerStateChange), arg0, arg1, arg2, arg3)
}

// LogOptimisticLockConflict mocks base method.
func (m *MockAuditLoggerInterface) LogOptimisticLockConflict(arg0 context.Context, arg1 string, arg2 uuid.UUID, arg3, arg4 int) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "LogOptimisticLockConflict", arg0, arg1, arg2, arg3, arg4)
}

// LogOptimisticLockConflict indicates an expected call of LogOptimisticLockConflict.
func (mr *MockAuditLoggerInterfaceMockRecorder) LogOptimisticLockConflict(arg0, arg1, arg2, arg3, arg4 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LogOptimisticLockConflict", reflect.TypeOf((*MockAuditLoggerInterface)(nil).LogOptimisticLockConflict), arg0, arg1, arg2, arg3, arg4)
}

// LogQueueItemEnqueued mocks base method.
func (m *MockAuditLoggerInterface) LogQueueItemEnqueued(arg0 context.Context, arg1, arg2 uuid.UUID, arg3 string, arg4 int) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "LogQueueItemEnqueued", arg0, arg1, arg2, arg3, arg4)
}

// LogQueueItemEnqueued indicates an expected call of LogQueueItemEnqueued.
func (mr *MockAuditLoggerInterfaceMockRecorder) LogQueueItemEnqueued(arg0, arg1, arg2, arg3, arg4 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LogQueueItemEnqueued", reflect.TypeOf((*MockAuditLoggerInterface)(nil).LogQueueItemEnqueued), arg0, arg1, arg2, arg3, arg4)
}

// LogQueueItemProcessed mocks base method.
func (m *MockAuditLoggerInterface) LogQueueItemProcessed(arg0 context.Context, arg1, arg2 uuid.UUID, arg3 string, arg4 int) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "LogQueueItemProcessed", arg0, arg1, arg2, arg3, arg4)
}

// LogQueueItemProcessed indicates an expected call of LogQueueItemProcessed.
func (mr *MockAuditLoggerInterfaceMockRecorder) LogQueueItemProcessed(arg0, arg1, arg2, arg3, arg4 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LogQueueItemProcessed", reflect.TypeOf((*MockAuditLoggerInterface)(nil).LogQueueItemProcessed), arg0, arg1, arg2, arg3, arg4)
}

// LogRetryAttempt mocks base method.
func (m *MockAuditLoggerInterface) LogRetryAttempt(arg0 context.Context, arg1, arg2 uuid.UUID, arg3, arg4 int, arg5 int64) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "LogRetryAttempt", arg0, arg1, arg2, arg3, arg4, arg5)
}

// LogRetryAttempt indicates an expected call of LogRetryAttempt.
func (mr *MockAuditLoggerInterfaceMockRecorder) LogRetryAttempt(arg0, arg1, arg2, arg3, arg4, arg5 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LogRetryAttempt", reflect.TypeOf((*MockAuditLoggerInterface)(nil).LogRetryAttempt), arg0, arg1, arg2, arg3, arg4, arg5)
}

// LogTransactionProcessingCompleted mocks base method.
func (m *MockAuditLoggerInterface) LogTransactionProcessingCompleted(arg0 context.Context, arg1 uuid.UUID, arg2 string, arg3 int64) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "LogTransactionProcessingCompleted", arg0, arg1, arg2, arg3)
}

// LogTransactionProcessingCompleted indicates an expected call of LogTransactionProcessingCompleted.
func (mr *MockAuditLoggerInterfaceMockRecorder) LogTransactionProcessingCompleted(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LogTransactionProcessingCompleted", reflect.TypeOf((*MockAuditLoggerInterface)(nil).LogTransactionProcessingCompleted), arg0, arg1, arg2, arg3)
}

// LogTransactionProcessingFailed mocks base method.
func (m *MockAuditLoggerInterface) LogTransactionProcessingFailed(arg0 context.Context, arg1 uuid.UUID, arg2, arg3 string, arg4 int) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "LogTransactionProcessingFailed", arg0, arg1, arg2, arg3, arg4)
}

// LogTransactionProcessingFailed indicates an expected call of LogTransactionProcessingFailed.
func (mr *MockAuditLoggerInterfaceMockRecorder) LogTransactionProcessingFailed(arg0, arg1, arg2, arg3, arg4 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LogTransactionProcessingFailed", reflect.TypeOf((*MockAuditLoggerInterface)(nil).LogTransactionProcessingFailed), arg0, arg1, arg2, arg3, arg4)
}

// LogTransactionProcessingStarted mocks base method.
func (m *MockAuditLoggerInterface) LogTransactionProcessingStarted(arg0 context.Context, arg1 uuid.UUID, arg2 string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "LogTransactionProcessingStarted", arg0, arg1, arg2)
}

// LogTransactionProcessingStarted indicates an expected call of LogTransactionProcessingStarted.
func (mr *MockAuditLoggerInterfaceMockRecorder) LogTransactionProcessingStarted(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LogTransactionProcessingStarted", reflect.TypeOf((*MockAuditLoggerInterface)(nil).LogTransactionProcessingStarted), arg0, arg1, arg2)
}

// LogTransactionStateChange mocks base method.
func (m *MockAuditLoggerInterface) LogTransactionStateChange(arg0 context.Context, arg1 uuid.UUID, arg2, arg3 string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "LogTransactionStateChange", arg0, arg1, arg2, arg3)
}

// LogTransactionStateChange indicates an expected call of LogTransactionStateChange.
func (mr *MockAuditLoggerInterfaceMockRecorder) LogTransactionStateChange(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LogTransactionStateChange", reflect.TypeOf((*MockAuditLoggerInterface)(nil).LogTransactionStateChange), arg0, arg1, arg2, arg3)
}

// LogTransferCompleted mocks base method.
func (m *MockAuditLoggerInterface) LogTransferCompleted(arg0 context.Context, arg1 uuid.UUID, arg2 int64, arg3, arg4 *uuid.UUID) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "LogTransferCompleted", arg0, arg1, arg2, arg3, arg4)
}

// LogTransferCompleted indicates an expected call of LogTransferCompleted.
func (mr *MockAuditLoggerInterfaceMockRecorder) LogTransferCompleted(arg0, arg1, arg2, arg3, arg4 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LogTransferCompleted", reflect.TypeOf((*MockAuditLoggerInterface)(nil).LogTransferCompleted), arg0, arg1, arg2, arg3, arg4)
}

// LogTransferFailed mocks base method.
func (m *MockAuditLoggerInterface) LogTransferFailed(arg0 context.Context, arg1 uuid.UUID, arg2 string, arg3 int64) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "LogTransferFailed", arg0, arg1, arg2, arg3)
}

// LogTransferFailed indicates an expected call of LogTransferFailed.
func (mr *MockAuditLoggerInterfaceMockRecorder) LogTransferFailed(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LogTransferFailed", reflect.TypeOf((*MockAuditLoggerInterface)(nil).LogTransferFailed), arg0, arg1, arg2, arg3)
}

// LogTransferIdempotencyCheck mocks base method.
func (m *MockAuditLoggerInterface) LogTransferIdempotencyCheck(arg0 context.Context, arg1 string, arg2 uuid.UUID, arg3 string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "LogTransferIdempotencyCheck", arg0, arg1, arg2, arg3)
}

// LogTransferIdempotencyCheck indicates an expected call of LogTransferIdempotencyCheck.
func (mr *MockAuditLoggerInterfaceMockRecorder) LogTransferIdempotencyCheck(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LogTransferIdempotencyCheck", reflect.TypeOf((*MockAuditLoggerInterface)(nil).LogTransferIdempotencyCheck), arg0, arg1, arg2, arg3)
}

// LogEvent mocks base method.
func (m *MockAuditLoggerInterface) LogEvent(arg0 context.Context, arg1 string, arg2 map[string]interface{}) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "LogEvent", arg0, arg1, arg2)
}

// LogEvent indicates an expected call of LogEvent.
func (mr *MockAuditLoggerInterfaceMockRecorder) LogEvent(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LogEvent", reflect.TypeOf((*MockAuditLoggerInterface)(nil).LogEvent), arg0, arg1, arg2)
}

// LogTransferInitiated mocks base method.
func (m *MockAuditLoggerInterface) LogTransferInitiated(arg0 context.Context, arg1, arg2, arg3 uuid.UUID, arg4, arg5 string, arg6 uuid.UUID) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "LogTransferInitiated", arg0, arg1, arg2, arg3, arg4, arg5, arg6)
}

// LogTransferInitiated indicates an expected call of LogTransferInitiated.
func (mr *MockAuditLoggerInterfaceMockRecorder) LogTransferInitiated(arg0, arg1, arg2, arg3, arg4, arg5, arg6 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LogTransferInitiated", reflect.TypeOf((*MockAuditLoggerInterface)(nil).LogTransferInitiated), arg0, arg1, arg2, arg3, arg4, arg5, arg6)
}

// MockMetricsRecorderInterface is a mock of MetricsRecorderInterface interface.
type MockMetricsRecorderInterface struct {
	ctrl     *gomock.Controller
	recorder *MockMetricsRecorderInterfaceMockRecorder
}

// MockMetricsRecorderInterfaceMockRecorder is the mock recorder for MockMetricsRecorderInterface.
type MockMetricsRecorderInterfaceMockRecorder struct {
	mock *MockMetricsRecorderInterface
}

// NewMockMetricsRecorderInterface creates a new mock instance.
func NewMockMetricsRecorderInterface(ctrl *gomock.Controller) *MockMetricsRecorderInterface {
	mock := &MockMetricsRecorderInterface{ctrl: ctrl}
	mock.recorder = &MockMetricsRecorderInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMetricsRecorderInterface) EXPECT() *MockMetricsRecorderInterfaceMockRecorder {
	return m.recorder
}

// IncrementCounter mocks base method.
func (m *MockMetricsRecorderInterface) IncrementCounter(arg0 string, arg1 map[string]string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "IncrementCounter", arg0, arg1)
}

// IncrementCounter indicates an expected call of IncrementCounter.
func (mr *MockMetricsRecorderInterfaceMockRecorder) IncrementCounter(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncrementCounter", reflect.TypeOf((*MockMetricsRecorderInterface)(nil).IncrementCounter), arg0, arg1)
}

// RecordGauge mocks base method.
func (m *MockMetricsRecorderInterface) RecordGauge(arg0 string, arg1 float64, arg2 map[string]string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RecordGauge", arg0, arg1, arg2)
}

// RecordGauge indicates an expected call of RecordGauge.
func (mr *MockMetricsRecorderInterfaceMockRecorder) RecordGauge(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordGauge", reflect.TypeOf((*MockMetricsRecorderInterface)(nil).RecordGauge), arg0, arg1, arg2)
}

// RecordProcessingTime mocks base method.
func (m *MockMetricsRecorderInterface) RecordProcessingTime(arg0 string, arg1 time.Duration) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RecordProcessingTime", arg0, arg1)
}

// RecordProcessingTime indicates an expected call of RecordProcessingTime.
func (mr *MockMetricsRecorderInterfaceMockRecorder) RecordProcessingTime(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordProcessingTime", reflect.TypeOf((*MockMetricsRecorderInterface)(nil).RecordProcessingTime), arg0, arg1)
}

// MockCircuitBreakerInterface is a mock of CircuitBreakerInterface interface.
type MockCircuitBreakerInterface struct {
	ctrl     *gomock.Controller
	recorder *MockCircuitBreakerInterfaceMockRecorder
}

// MockCircuitBreakerInterfaceMockRecorder is the mock recorder for MockCircuitBreakerInterface.
type MockCircuitBreakerInterfaceMockRecorder struct {
	mock *MockCircuitBreakerInterface
}

// NewMockCircuitBreakerInterface creates a new mock instance.
func NewMockCircuitBreakerInterface(ctrl *gomock.Controller) *MockCircuitBreakerInterface {
	mock := &MockCircuitBreakerInterface{ctrl: ctrl}
	mock.recorder = &MockCircuitBreakerInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCircuitBreakerInterface) EXPECT() *MockCircuitBreakerInterfaceMockRecorder {
	return m.recorder
}

// GetFailureCount mocks base method.
func (m *MockCircuitBreakerInterface) GetFailureCount() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFailureCount")
	ret0, _ := ret[0].(int)
	return ret0
}

// GetFailureCount indicates an expected call of GetFailureCount.
func (mr *MockCircuitBreakerInterfaceMockRecorder) GetFailureCount() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFailureCount", reflect.TypeOf((*MockCircuitBreakerInterface)(nil).GetFailureCount))
}

// GetState mocks base method.
func (m *MockCircuitBreakerInterface) GetState() models.CircuitBreakerState {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetState")
	ret0, _ := ret[0].(models.CircuitBreakerState)
	return ret0
}

// GetState indicates an expected call of GetState.
func (mr *MockCircuitBreakerInterfaceMockRecorder) GetState() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetState", reflect.TypeOf((*MockCircuitBreakerInterface)(nil).GetState))
}

// IsOpen mocks base method.
func (m *MockCircuitBreakerInterface) IsOpen() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsOpen")
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsOpen indicates an expected call of IsOpen.
func (mr *MockCircuitBreakerInterfaceMockRecorder) IsOpen() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsOpen", reflect.TypeOf((*MockCircuitBreakerInterface)(nil).IsOpen))
}

// RecordFailure mocks base method.
func (m *MockCircuitBreakerInterface) RecordFailure() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RecordFailure")
}

// RecordFailure indicates an expected call of RecordFailure.
func (mr *MockCircuitBreakerInterfaceMockRecorder) RecordFailure() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordFailure", reflect.TypeOf((*MockCircuitBreakerInterface)(nil).RecordFailure))
}

// RecordSuccess mocks base method.
func (m *MockCircuitBreakerInterface) RecordSuccess() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RecordSuccess")
}

// RecordSuccess indicates an expected call of RecordSuccess.
func (mr *MockCircuitBreakerInterfaceMockRecorder) RecordSuccess() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordSuccess", reflect.TypeOf((*MockCircuitBreakerInterface)(nil).RecordSuccess))
}

// Reset mocks base method.
func (m *MockCircuitBreakerInterface) Reset() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Reset")
}

// Reset indicates an expected call of Reset.
func (mr *MockCircuitBreakerInterfaceMockRecorder) Reset() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Reset", reflect.TypeOf((*MockCircuitBreakerInterface)(nil).Reset))
}

// MockCustomerLoggerInterface is a mock of CustomerLoggerInterface interface.
type MockCustomerLoggerInterface struct {
	ctrl     *gomock.Controller
	recorder *MockCustomerLoggerInterfaceMockRecorder
}

// MockCustomerLoggerInterfaceMockRecorder is the mock recorder for MockCustomerLoggerInterface.
type MockCustomerLoggerInterfaceMockRecorder struct {
	mock *MockCustomerLoggerInterface
}

// NewMockCustomerLoggerInterface creates a new mock instance.
func NewMockCustomerLoggerInterface(ctrl *gomock.Controller) *MockCustomerLoggerInterface {
	mock := &MockCustomerLoggerInterface{ctrl: ctrl}
	mock.recorder = &MockCustomerLoggerInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCustomerLoggerInterface) EXPECT() *MockCustomerLoggerInterfaceMockRecorder {
	return m.recorder
}

// LogAccountCreatedForCustomer mocks base method.
func (m *MockCustomerLoggerInterface) LogAccountCreatedForCustomer(arg0 context.Context, arg1, arg2, arg3 uuid.UUID, arg4 string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "LogAccountCreatedForCustomer", arg0, arg1, arg2, arg3, arg4)
}

// LogAccountCreatedForCustomer indicates an expected call of LogAccountCreatedForCustomer.
func (mr *MockCustomerLoggerInterfaceMockRecorder) LogAccountCreatedForCustomer(arg0, arg1, arg2, arg3, arg4 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LogAccountCreatedForCustomer", reflect.TypeOf((*MockCustomerLoggerInterface)(nil).LogAccountCreatedForCustomer), arg0, arg1, arg2, arg3, arg4)
}

// LogAccountOwnershipTransferred mocks base method.
func (m *MockCustomerLoggerInterface) LogAccountOwnershipTransferred(arg0 context.Context, arg1, arg2, arg3, arg4 uuid.UUID) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "LogAccountOwnershipTransferred", arg0, arg1, arg2, arg3, arg4)
}

// LogAccountOwnershipTransferred indicates an expected call of LogAccountOwnershipTransferred.
func (mr *MockCustomerLoggerInterfaceMockRecorder) LogAccountOwnershipTransferred(arg0, arg1, arg2, arg3, arg4 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LogAccountOwnershipTransferred", reflect.TypeOf((*MockCustomerLoggerInterface)(nil).LogAccountOwnershipTransferred), arg0, arg1, arg2, arg3, arg4)
}

// LogAuthorizationFailure mocks base method.
func (m *MockCustomerLoggerInterface) LogAuthorizationFailure(arg0 context.Context, arg1 string, arg2 uuid.UUID, arg3 string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "LogAuthorizationFailure", arg0, arg1, arg2, arg3)
}

// LogAuthorizationFailure indicates an expected call of LogAuthorizationFailure.
func (mr *MockCustomerLoggerInterfaceMockRecorder) LogAuthorizationFailure(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LogAuthorizationFailure", reflect.TypeOf((*MockCustomerLoggerInterface)(nil).LogAuthorizationFailure), arg0, arg1, arg2, arg3)
}

// LogCustomerCreated mocks base method.
func (m *MockCustomerLoggerInterface) LogCustomerCreated(arg0 context.Context, arg1 uuid.UUID, arg2 string, arg3 uuid.UUID) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "LogCustomerCreated", arg0, arg1, arg2, arg3)
}

// LogCustomerCreated indicates an expected call of LogCustomerCreated.
func (mr *MockCustomerLoggerInterfaceMockRecorder) LogCustomerCreated(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LogCustomerCreated", reflect.TypeOf((*MockCustomerLoggerInterface)(nil).LogCustomerCreated), arg0, arg1, arg2, arg3)
}

// LogCustomerDeleted mocks base method.
func (m *MockCustomerLoggerInterface) LogCustomerDeleted(arg0 context.Context, arg1 uuid.UUID, arg2 int, arg3 uuid.UUID) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "LogCustomerDeleted", arg0, arg1, arg2, arg3)
}

// LogCustomerDeleted indicates an expected call of LogCustomerDeleted.
func (mr *MockCustomerLoggerInterfaceMockRecorder) LogCustomerDeleted(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LogCustomerDeleted", reflect.TypeOf((*MockCustomerLoggerInterface)(nil).LogCustomerDeleted), arg0, arg1, arg2, arg3)
}

// LogCustomerEmailUpdated mocks base method.
func (m *MockCustomerLoggerInterface) LogCustomerEmailUpdated(arg0 context.Context, arg1 uuid.UUID, arg2, arg3 string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "LogCustomerEmailUpdated", arg0, arg1, arg2, arg3)
}

// LogCustomerEmailUpdated indicates an expected call of LogCustomerEmailUpdated.
func (mr *MockCustomerLoggerInterfaceMockRecorder) LogCustomerEmailUpdated(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LogCustomerEmailUpdated", reflect.TypeOf((*MockCustomerLoggerInterface)(nil).LogCustomerEmailUpdated), arg0, arg1, arg2, arg3)
}

// LogCustomerProfileUpdated mocks base method.
func (m *MockCustomerLoggerInterface) LogCustomerProfileUpdated(arg0 context.Context, arg1 uuid.UUID, arg2 []string, arg3 uuid.UUID) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "LogCustomerProfileUpdated", arg0, arg1, arg2, arg3)
}

// LogCustomerProfileUpdated indicates an expected call of LogCustomerProfileUpdated.
func (mr *MockCustomerLoggerInterfaceMockRecorder) LogCustomerProfileUpdated(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LogCustomerProfileUpdated", reflect.TypeOf((*MockCustomerLoggerInterface)(nil).LogCustomerProfileUpdated), arg0, arg1, arg2, arg3)
}

// LogCustomerSearchCompleted mocks base method.
func (m *MockCustomerLoggerInterface) LogCustomerSearchCompleted(arg0 context.Context, arg1 int, arg2 int64) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "LogCustomerSearchCompleted", arg0, arg1, arg2)
}

// LogCustomerSearchCompleted indicates an expected call of LogCustomerSearchCompleted.
func (mr *MockCustomerLoggerInterfaceMockRecorder) LogCustomerSearchCompleted(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LogCustomerSearchCompleted", reflect.TypeOf((*MockCustomerLoggerInterface)(nil).LogCustomerSearchCompleted), arg0, arg1, arg2)
}

// LogCustomerSearchFailed mocks base method.
func (m *MockCustomerLoggerInterface) LogCustomerSearchFailed(arg0 context.Context, arg1 string, arg2 int64) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "LogCustomerSearchFailed", arg0, arg1, arg2)
}

// LogCustomerSearchFailed indicates an expected call of LogCustomerSearchFailed.
func (mr *MockCustomerLoggerInterfaceMockRecorder) LogCustomerSearchFailed(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LogCustomerSearchFailed", reflect.TypeOf((*MockCustomerLoggerInterface)(nil).LogCustomerSearchFailed), arg0, arg1, arg2)
}

// LogCustomerSearchStarted mocks base method.
func (m *MockCustomerLoggerInterface) LogCustomerSearchStarted(arg0 context.Context, arg1, arg2 string, arg3 uuid.UUID) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "LogCustomerSearchStarted", arg0, arg1, arg2, arg3)
}

// LogCustomerSearchStarted indicates an expected call of LogCustomerSearchStarted.
func (mr *MockCustomerLoggerInterfaceMockRecorder) LogCustomerSearchStarted(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LogCustomerSearchStarted", reflect.TypeOf((*MockCustomerLoggerInterface)(nil).LogCustomerSearchStarted), arg0, arg1, arg2, arg3)
}

// LogPasswordChanged mocks base method.
func (m *MockCustomerLoggerInterface) LogPasswordChanged(arg0 context.Context, arg1 uuid.UUID) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "LogPasswordChanged", arg0, arg1)
}

// LogPasswordChanged indicates an expected call of LogPasswordChanged.
func (mr *MockCustomerLoggerInterfaceMockRecorder) LogPasswordChanged(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LogPasswordChanged", reflect.TypeOf((*MockCustomerLoggerInterface)(nil).LogPasswordChanged), arg0, arg1)
}

// LogPasswordReset mocks base method.
func (m *MockCustomerLoggerInterface) LogPasswordReset(arg0 context.Context, arg1, arg2 uuid.UUID) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "LogPasswordReset", arg0, arg1, arg2)
}

// LogPasswordReset indicates an expected call of LogPasswordReset.
func (mr *MockCustomerLoggerInterfaceMockRecorder) LogPasswordReset(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LogPasswordReset", reflect.TypeOf((*MockCustomerLoggerInterface)(nil).LogPasswordReset), arg0, arg1, arg2)
}

// LogValidationFailure mocks base method.
func (m *MockCustomerLoggerInterface) LogValidationFailure(arg0 context.Context, arg1, arg2 string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "LogValidationFailure", arg0, arg1, arg2)
}

// LogValidationFailure indicates an expected call of LogValidationFailure.
func (mr *MockCustomerLoggerInterfaceMockRecorder) LogValidationFailure(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LogValidationFailure", reflect.TypeOf((*MockCustomerLoggerInterface)(nil).LogValidationFailure), arg0, arg1, arg2)
}
